In [47]:
import numpy as np

title = 'NumPy and Arrays 🚀'

### 1 - Create NumPy Array

The 1-D array can be created by using the function `array()` which takes a list of values as argument and returns the a 1-D array

In [11]:
one_dimen_array = np.array([1, 2, 3])
print(one_dimen_array)

[1 2 3]


Another method of creating an array is using the `np.arrange(value)` which returns an array of positive values within the given interval

In [21]:
# negatives do not apply here
# creates an array of 5 integers from 0 to the specified value
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [20]:
# create an array from 1 to 20 with a gap of 4
# np.arange(start, stop, step)
a = np.arange(1, 20, 4)
print(a)

[ 1  5  9 13 17]


In [29]:
# create an array with 3 evenly spaced values from 0 to 40
line_spaced_arr = np.linspace(0, 40, 3)
print(f'line spaced array: {line_spaced_arr}')

# remove the default floating point (np.float64) from the `np.linespace`
# by specifying the data type as another parameter
line_spaced_arr_int = np.linspace(0, 40, 3, dtype=int)
print(f'line spaced array int: {line_spaced_arr_int}')

# using previous example
c_float = np.arange(1, 10, 2, dtype=float)
print(f'c_float: {c_float}')

char_arr = np.array([title])
print(f'char array: {char_arr}')
print(f'data type: {char_arr.dtype}')

line spaced array: [ 0. 20. 40.]
line spaced array int: [ 0 20 40]
c_float: [1. 3. 5. 7. 9.]
char array: ['NumPy and Arrays 🚀']
data type: <U18


In [ ]:
# Return an array setting values to one
ones_arr = np.ones(3)
print('ones_arr: ', ones_arr)

# Return a new array setting values to zero
zeros_arr = np.zeros(3, dtype=int)
print('zeros_arr: ', zeros_arr)

# Return a new array of shape 3, without initializing entries.
print('empty arr: ', np.empty(3))

# Return a new array of shape 3 with random numbers between 0 and 1.
rand_arr = np.random.rand(3)
print('random array: ', rand_arr)

ones_arr:  [1. 1. 1.]
zeros_arr:  [0 0 0]
empty arr:  [0. 0. 0.]
random array:  [0.45615188 0.85092908 0.01764149]


### 2 - Multidimensional Arrays

A two dimensional array has more than one column.

In [38]:
# Create a 2 dimensional array
two_dimen = np.array([[1, 2, 5], [5, 3, 7]])
print('2-D array : ', two_dimen)

2-D array :  [[1 2 5]
 [5 3 7]]


An alternative way to create a 2-D array is to create a 1-D array and reshape it.

In [43]:
# create a 1-D array
one_dim = np.array([1, 2, 3, 4, 5, 6])

# apply the reshape() method which returns a 2-D array
two_dim = np.reshape(one_dim, (2, 3))
print('2-D array: ', two_dim)

# Return the dimension of the 2-D
print('dimension: ', two_dim.ndim)

# Return the shape of the 2-D
print('shape: ', two_dim.shape)

# Return the size of the 2-D
print('size: ', two_dim.size)

2-D array:  [[1 2 3]
 [4 5 6]]
dimension:  2
shape:  (2, 3)
size:  6


You can also perform maths operations on arrays as seen below:

In [46]:
array_one = np.array([2, 4, 6])
array_two = np.array([1, 3, 5])

print('sum: ', array_one + array_two)
print('substraction: ', array_one - array_two)
print('multiplication: ', array_one * array_two)

sum:  [ 3  7 11]
substraction:  [1 1 1]
multiplication:  [ 2 12 30]
